[2024-07-02T17:07:12.323+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: SNOWFLAKE_RAW.pokemon_raw scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T17:07:12.329+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: SNOWFLAKE_RAW.pokemon_raw scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T17:07:12.329+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-02T17:07:12.329+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-07-02T17:07:12.329+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-02T17:07:12.343+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): pokemon_raw> on 2024-07-01 00:00:00+00:00
[2024-07-02T17:07:12.345+0000] {standard_task_runner.py:55} INFO - Started process 7138 to run task
[2024-07-02T17:07:12.350+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'SNOWFLAKE_RAW', 'pokemon_raw', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/SNOWFLAKE_RAW_dag.py', '--cfg-path', '/tmp/tmpw1tlu9gi']
[2024-07-02T17:07:12.350+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask pokemon_raw
[2024-07-02T17:07:12.400+0000] {task_command.py:388} INFO - Running <TaskInstance: SNOWFLAKE_RAW.pokemon_raw scheduled__2024-07-01T00:00:00+00:00 [running]> on host data-flow-tol.us-central1-b.c.our-velocity-427103-n8.internal
[2024-07-02T17:07:12.444+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=SNOWFLAKE_RAW
AIRFLOW_CTX_TASK_ID=pokemon_raw
AIRFLOW_CTX_EXECUTION_DATE=2024-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-01T00:00:00+00:00
[2024-07-02T17:07:12.446+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/jacksonlmakl/data_flow_tool/airflow_home/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/jacksonlmakl/data_flow_tool/airflow_home/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/jacksonlmakl/data_flow_tool/airflow_home/dags/SNOWFLAKE_RAW_dag.py", line 16, in task_function
    exec(open(script_path).read())
FileNotFoundError: [Errno 2] No such file or directory: '/home/jacksonlmakl/data_flow_tool/airflow_home/dags/SNOWFLAKE_RAW_scripts/pokemon_raw.py'
[2024-07-02T17:07:12.449+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=SNOWFLAKE_RAW, task_id=pokemon_raw, execution_date=20240701T000000, start_date=20240702T170712, end_date=20240702T170712
[2024-07-02T17:07:12.459+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 3 for task pokemon_raw ([Errno 2] No such file or directory: '/home/jacksonlmakl/data_flow_tool/airflow_home/dags/SNOWFLAKE_RAW_scripts/pokemon_raw.py'; 7138)
[2024-07-02T17:07:12.481+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-02T17:07:12.494+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
